# Generated by Django 2.2.5 on 2019-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'account',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
