# Generated by Django 2.2.5 on 2019-09-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'ordering': ('name',)},
        ),
    ]
