# Generated by Django 2.2.5 on 2019-09-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190922_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='post',
            field=models.ManyToManyField(to='app.PostModel'),
        ),
    ]
