# Generated by Django 2.2.5 on 2019-09-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190922_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(to='app.TagModel'),
        ),
    ]
